---
    - hosts: instruct
      become: yes
      remote_user: ubuntu
      tasks:
      - name: Update packages
        apt:
          update_cache: yes

      - name: add github ssh key!
        copy: >
          src=files/id_rsa.github
          dest=/root/.ssh/id_rsa.github
          owner=root
          group=root
          mode=0600
    
      - name: configure ssh to use ansible key for github.com!
        template: >
          src=templates/ssh_config.j2
          dest=/root/.ssh/config
          owner=root
          group=root
          mode=064
    
      - git:
          repo: git@github.com:felipteixeira/python.git
          version: master
          accept_hostkey: yes
          key_file: /root/.ssh/id_rsa.github
          dest: /home/ubuntu/app/python
    
      - name: install Docker, run MinIO container, export variables, install dependencies and run the serve via shell-script!
        script: /home/ubuntu/instruct-auto/scripts.sh \
                1> /tmp/install.output.log \
                2> /tmp/install.error.log

      - name: create a file to send to MinIO!
        shell: touch /tmp/fileToSendToMinIO
        args:
          warn: no
    
      - name: send file using POST to MinIO bucket!
        shell: curl -X POST -F "file=@/tmp/fileToSendToMinIO" http://52.14.169.24:5000/minio-upload/bucket-teste/fileToSendToMinIO
        args:
          warn: no